### ISSUE TITLE
players for a game should include the play creator

### ISSUE THREAD

**Issue by koedbymonkey** [meeples/meeples#49]
https://meeples-staging.herokuapp.com/games/1
players does not include the play creator

**Comment by BM5k** [comment]
rolling this forward

**Comment by mtchavez** [comment]
Should we assign this to someone else since it is a bug and hasn't seen action in a few weeks? Or can @bowerman bug @koedbymonkey to do this with him?

**Comment by mtchavez** [comment]
Closed by #90
