### ISSUE TITLE
Github Sign In

### ISSUE THREAD

**Issue by mtchavez** [meeples/meeples#69]
Error signing into github on production.

```
https://meeples-production.herokuapp.com/users/auth/github?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=3dc8c3c3c76bee6e16a831d4b5b6156edf1b29d8f4f8cfa2
```

**Comment by mtchavez** [comment]
Callback base URL needs to be changed to `https://meeples.herokuapp.com` so whoever created it can you please update? @BM5k @bowerman

**Comment by BM5k** [comment]
I updated the application URLs. Apparently, the meeples development and production applications are owned by @devfu. I’m trying to figure out how to transfer them to the @meeples org.

If transferring them isn’t easy, we could delete the apps and recreate them.
