### ISSUE TITLE
Vagrant Setup

### ISSUE THREAD

**Issue by mtchavez** [meeples/meeples#72]
Initial Requirements:

- [x] Ubuntu 14.04 LTS
- [x] RVM with Ruby 2.2.0 and bundler
- [x] ~~Unicorn serving the app~~ (handled by bundler no provisioning needed)
- [x] Redis 2.8.19
- [x] Postgres 9.4
- [x] Phantomjs for headless browser testing
- [x] Nodejs 0.12.0 for coffeescript and assets and JS engine
- [x] Memcached 1.4.22 just in case (being used in prod)

**Comment by BM5k** [comment]
I've had some issues running the latest phantomjs on OS X.  I'm running 1.9.2.

**Comment by mtchavez** [comment]
Only thing I think might be missing is we have a Memcache add on in production that I am not sure we are using. If we plan on using that then we should add memcache since it is stupid simple to add. But if it is just for production caching maybe the staging environment will be a better testing environment for that. Thoughts?

**Comment by mtchavez** [comment]
@BM5k I'll make a note of that when adding Phantomjs. Good to know.

**Comment by BM5k** [comment]
I think we’re using memcached just for asset cache during compilation, if I remember correctly.

Our tests aren’t using it, and caching is disabled in development mode, but I don’t think that’s a good reason to _not_ install it.

**Comment by mtchavez** [comment]
OK. Added memcached to list.

**Comment by mtchavez** [comment]
Box made, need to test it out and see how far off it is from being done.

**Comment by BM5k** [comment]
@mtchavez how do I test this?

**Comment by mtchavez** [comment]
#81 is an open pull request to address this that should have some information on what to do.
