### ISSUE TITLE
play page should link back to the game

### ISSUE THREAD

**Issue by BM5k** [meeples/meeples#87]
This might be a new story.

![screen shot 2015-03-06 at 11 13 44 am](https://cloud.githubusercontent.com/assets/29762/6530899/13a25e2c-c3f2-11e4-9673-7079f473799f.png)

**Comment by mtchavez** [comment]
I agree. If it doesn't link back already lets add it.

**Comment by BM5k** [comment]
@mtchavez new story or bug?

**Comment by mtchavez** [comment]
Probably not a bug.

**Comment by BM5k** [comment]
Added to agilatr: https://www.agilatr.com/projects/bm5k-meepl-es/stories/44
