### ISSUE TITLE
Do we still need “You can vote for us in the 2014 Rails Rumble!” on every page?

### ISSUE THREAD

**Issue by BM5k** [meeples/meeples#89]
![screen shot 2015-03-06 at 11 21 50 am](https://cloud.githubusercontent.com/assets/29762/6531039/0cb69a5a-c3f3-11e4-8dde-01a17bfcdb59.png)

**Comment by mtchavez** [comment]
I *vote* no.

**Comment by BM5k** [comment]
I see what you did there.

**Comment by BM5k** [comment]
Closed by #92
