### ISSUE TITLE
features/users_spec.rb:18 fails randomly

### ISSUE THREAD

**Issue by BM5k** [meeples/meeples#95]
Expects to find `devise.registrations.signed_up_but_unconfirmed` on the page, but is apparently finding `devise.registrations.signed_up` instead.

**Comment by BM5k** [comment]
Travis output: https://travis-ci.org/meeples/meeples/builds/53577317#L484-L487

**Comment by BM5k** [comment]
Opened plataformatec/devise#3507

**Comment by bowerman** [comment]
maybe this will be okay :cat:?

**Comment by BM5k** [comment]
Yeah. I vote we leave this issue open until we go a few days without this problem showing up again.

**Comment by BM5k** [comment]
There’s been 0 related build failures in almost a week. Closing this issue. Will re-open if this pops up again.
